### PR TITLE
Use CPM

### PR DESCRIPTION
**Pull request by data-man**
Also let's try to always use the latest dependencies.

### CODE REVIEW

**Comment by data-man** [comment]
Personally I'd rather switch to another testing library.
E.g. to doctest or Boost's μt.

**Comment by christianparpart** [comment]
I will have a look in here asap.

But with regards to boost hmmm. I am open for alternatives if they give an additional benefit, but boost is rather low on the list of the alternatives. I do not know do test yet :)

**Comment by data-man** [comment]
Boost's μt is independent of other Boost's libraries.
Only std С++17 is needed.

**Comment by christianparpart** [comment]
@data-man I'd like to merge this BUT what do you think, will this (and then later integrated into contour) also work with launchpad PPA buildbots? There the build has to be completely offline as you don't have access to the internet (see CI ppa build workflow).

The other main concern I am having is that in your patch we fetch the latest state of each dependency. This might break our CI unindentionally due to failures on the 3rdparties. Don't you think it's best to just tag the latest (stable) release and use that, so we're sure to always employ an expected result? I'd highly prefer that, otherwise builds of our same git tag will inevitably be different depending on the time of the build time (due to 3rdparties).

**Comment by data-man** [comment]
I think about new CMake options in `Contour`:
- [ ] `Use system's libs` (or something like this).
- [ ] `Use latest libs` (or something like this).

**Comment by data-man** [comment]
> we fetch the latest state of each dependency. This might break our CI unindentionally due to failures on the 3rdparties.

Good point!
Will change it soon. :tm:

**Comment by data-man** [comment]
BTW currently `libunicode` isn't tagged.

**Comment by christianparpart** [comment]
> BTW currently `libunicode` isn't tagged.

oh yes it can deserve an official initial release. Until now contour was depending against a Git SHA for referencing the right (latest) version. We can release a 0.1.0 though, yeah.

**Comment by christianparpart** [comment]
> I think about new CMake options in `Contour`:
> 
>     * [ ]  `Use system's libs` (or something like this).
> 
>     * [ ]  `Use latest libs` (or something like this).

I am curios to see how you think you want to tackle that. The first one should be easy, the latter one I'd suggest to instead of say "latest" to allow explicitly specifying the version/SHA one wants to build against. That is actually possible with FetchContent too.

**Comment by data-man** [comment]
> That is actually possible with FetchContent too.

CPM is a powerful wrapper on top of it. :) (but requires CMake 3.14 at least).
Changed to draft.

**Comment by data-man** [comment]
I hope it's ready for review.

**Comment by christianparpart** [comment]
I am having a look tonight. Thanks.

**Review by christianparpart — APPROVED** [review]
LGTM :pray: :)

**Pull request merged**
